### ISSUE TITLE
Q-C_2: Trim whitespaces from config params

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins-QualityAssessment#15]
When taking values from the configuration (subject class URIs, predicate URIs), please trim the whitespaces. Because if you insert e.g. "http://purl.org/dc/terms/title " it will fail with strange error. 

Solution: Always trim whitespaces before saving configuration from the dialog

**Comment by AndreAga** [comment]
@tomas-knap I'm doing it :)
