### ISSUE TITLE
Report  of QA DPUs uses wrong predicate

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins-QualityAssessment#16]
Report of QA DPUs uses: 
http://purl.org/dc/elements/1.1/date

But "http://purl.org/dc/terms/date" should be used.

**Comment by AndreAga** [comment]
@tomas-knap that value is placed by org.openrdf.model.vocabulary.DC. I don't redefine it. Have I to create a custom URI in QualityAntology?

**Comment by tomas-knap** [comment]
Please use label "ready for test" when it is ready for me to test it.

**Comment by AndreAga** [comment]
@tomas-knap I'm sorry. Check if now Q-C_2 and Q-ACC_1 use the correct Date predicate.
