### ISSUE TITLE
Prepere DPUs Q-ACC1, Q-ACC4, Q-ACC6, Q-C-2, Q-C-5 for releasing

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins-QualityAssessment#17]
TODO: 
1) As we discussed it is necessary to update readme of DPUs with the information stating what is not yet implemented, why we did not reach the goal - e.g. the problems of RDF Unit in Q-ACC1 have to be described, limitation of Q-ACC1 have to be introduced. Without this, DPUs cannot be released. 
2) Q-ACC6 - there must be explanation of regular expressions. So when selecting certain regular expression, there must be at least paragraph of plain English explaining the idea of the regular expression behind and some samples. Otherwise useless, as the user does not know what the DPU is actually doing.
3) Before release, pom.xml of the DPUs has to be adjusted based on the latest changes. Discussion with me is needed in this point. 
4) feature/Q-ACC_4, feature/Q-ACC_6, feature/Q-C_5 must be merged to develop (see the corresponding issues)

I did not see any progress from UNIMIB from the call with Anisa last week (regarding 1-2), where we discuss what has to be adjusted, also 3) is not instant,  so the plugins in the subj will be released in July.

**Comment by tomas-knap** [comment]
I assigned to @AndreAga, but ask Anisa, if that is ok. Also Anisa has details to 1)-2)

**Comment by anisaR** [comment]
After our skype call I was off two days so you couldn't expect a progress done in such a short time. On the other side we have been waiting from your feedback since April and never had an answer. So please try to be fair.

**Comment by tomas-knap** [comment]
5) localization of the DPUs which should be released (with at least English localization package)

**Comment by AndreAga** [comment]
@tomas-knap I just committed the updated readme of Q-ACC_1.

**Comment by tomas-knap** [comment]
Thanks, regarding 3), pom.xml adjustments. Basically please take this pom.xml (https://github.com/UnifiedViews/Plugins/blob/develop/t-filesFilter/pom.xml) as the template and adjust your pom.xml's for the 5 DPUs in the subj based on that. In particular it is necessary to adjust: 

1) parent pom.xml version
2) specify groupID as in the template
3) specify artifactID in the similar way as in the template (uv-t-xx)
4) specify name in the similar way (T-xx)
5) version should be snapshot version
6) properties element should be adjusted as in the template
7) dependencies on UV libraries (e.g. uv-dataunit-helpers) should be without versions, versions are provided by the parent pom.xml

Please let me know when this is done

**Comment by skrchnavy** [comment]
I suggest to use group ID as eu.unifiedviews.plugins.quality, then it will be in repository in extra directory.

**Comment by tomas-knap** [comment]
Yes groupID should be eu.unifiedviews.plugins.quality

**Comment by tomas-knap** [comment]
Regarding the names/artifactID, I suggest to have better names than q-acc6, because the user who is not familiar with D3.2 will not understand. So please try to use better ids/names, which are more descriptive. Reference to q-acc6 can be mentioned e.g. in the description of the DPU (e.g., This DPU was developed as part of COMSODE.eu project, where it was denoted as Q-acc6)

**Comment by AndreAga** [comment]
@tomas-knap Please check if it's right.

**Comment by tomas-knap** [comment]
@AndreAga As I suggested above, please add to each pom.xml (e.g. to description of the DPU) the reference to the COMSODE ID (Q_ACC1 etc.).

**Comment by AndreAga** [comment]
@tomas-knap Done.

**Comment by tomas-knap** [comment]
@AndreAga Please update also description of the DPUs in README and also Description element in pom.xml, so that it is clear what the DPU is doing. For example by checking https://github.com/UnifiedViews/Plugins-QualityAssessment/tree/develop/Q-CompletenessChecker, the desc "Check the missing elements from a specified list of subject/property." is not clear, please describe in more detail, e.g., User may specify list of tuples - RDF class and RDF predicate. The DPU then checks  for each tuple whether instances of the RDF class contain the specified RDF predicate. At the end, DPU computes completeness score for each class and predicate, ...."

**Comment by AndreAga** [comment]
@tomas-knap Ok, @anisaR please prepare them and let me have asap.

**Comment by tomas-knap** [comment]
@AndreAga Regarding the names of the DPUs, please update it as follows:
Q-CompletenessChecker -> q-rdfCompletenessChecker
Q-NumericalRangeChecker -> q-rdfLiteralNumericRangeChecker
Q-PatternChecker -> q-rdfLiteralRegualExpressionPaternChecker
Q-RDFValidator -> q-rdfSyntacticValidator
Q-ResourceUnderstandability ->  q-rdfResourceUnderstandability

Please use also lower "q" and start with lower letter in the names of the DPU folders. Regarding artifact IDs, names of DPUs in pom.xml - the format is ok (lower letters for artifactID, starting upper letter for names). 

Please update artifactID, name in pom.xml, folder with the DPU and in README. It is not necessary to update main/config/dialog classes or packages.

**Comment by tomas-knap** [comment]
@AndreAga Regarding "eu.unifiedviews.plugins.quality.qualitygraph" dependency, which is refered from the DPUs, where is this library available? Are the source codes available for it?

**Comment by AndreAga** [comment]
@tomas-knap QualityGraph is in Q_CU branch with the cited DPU.

**Comment by tomas-knap** [comment]
Ok, so please put the QualityOntology to develop (only QualityOntology folder, not Q_CU). README of every QA DPU must be updated and there must be a note in Developer's notes that this library is required.

**Comment by AndreAga** [comment]
Have I to update also the package of each DPU?

**Comment by tomas-knap** [comment]
Do you mean due to changes in DPU names? No that is not necessary

**Comment by tomas-knap** [comment]
Otherwise it seems to be OK, I will check once again when your changes above are done. Please also test that every adjusted DPU can by built and deployed to UnifiedViews.

**Comment by tomas-knap** [comment]
Thanks!

**Comment by AndreAga** [comment]
You're welcome

**Comment by tomas-knap** [comment]
Thanks, names looks ok. Just regarding qualityOntology, please do not name it q-rdfQualityOntology (the previous name was ok), so that it does not look like a DPU. And also to the developers' notes, please put reference (link) to the qualityOntology. Thanks.

As discusses with @skrchnavy, we need to close this today if it should be in release 2.1, so please ping @anisaR, so that the descriptions are ready today.

**Comment by AndreAga** [comment]
@tomas-knap She's working on it, I think they'll be ready today.

**Comment by AndreAga** [comment]
@tomas-knap DPUs are ready.

**Comment by skrchnavy** [comment]
@tomas-knap / @AndreAga - milestone set to 2.1.0, was this issue included in the release 2.1.0?
