### ISSUE TITLE
Documentation of release QA DPUs must be updated

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins-QualityAssessment#24]
Documentation (README, CHANGELOG, user doc) of all DPUs releases in master branch should be updated based on:

https://grips.semantic-web.at/display/UDDOC/Tutorial%3A+Creating+skeleton+files+for+new+DPU

Updates should go to develop branch!

**Comment by vcutrona** [comment]
@tomas-knap we have updated doc for each DPU.
