### ISSUE TITLE
Q_ACC1:Cannot build the DPU, missing external dependency

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins-QualityAssessment#8]
Branch feature Q_ACC_1, commit 7db35847a93aa43d76c94439a0bfb3622abe7c09

This dependency is missing, I cannot  build the DPU
 
<dependency>
        <groupId>eu.unifiedviews.plugins.quality.qualitygraph</groupId>
        <artifactId>uv-q-qualityOntology</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <scope>compile</scope>
    </dependency>

To reproduce: Try mvn clean install on fresh computer

Log: 

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.735s
[INFO] Finished at: Tue Mar 24 09:43:37 CET 2015
[INFO] Final Memory: 9M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project Q-ACC_1: Could not resolve dependencies for project eu.unifiedviews:Q-ACC_1:bundle:1.0.0: Could not find artifact eu.unifiedviews.plugins.quality.qualitygraph:uv-q-qualityOntology:jar:0.0.1-SNAPSHOT -> [Help 1]
[ERROR] 

```

**Comment by tomas-knap** [comment]
Note: the same problem is for all DPUs. 

Please put also ug-q-qualityOntology source codes to the repository, so that I can observe the code, build it.

**Comment by anisaR** [comment]
The branch Q-CU_1 contains the ug-q-qualityOntology source code. So please, try to comiple the Q-CU_1 first and the problem shouldn't persist.

**Comment by tomas-knap** [comment]
Just tested, switched to Q-CU_1, but the same error occurs: 

Downloading: http://www.eclipse.org/downloads/download.php?r=1&nf=1&file=/rt/eclipselink/maven.repo/eu/unifiedviews/dataunit-relational-impl/1.0.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://maven.eea.sk/artifactory/public/eu/unifiedviews/dataunit-relational-impl/1.0.0-SNAPSHOT/maven-metadata.xml (2 KB at 6.6 KB/sec)
Downloading: https://repo.eclipse.org/content/repositories/snapshots/eu/unifiedviews/dataunit-relational-impl/1.0.0-SNAPSHOT/maven-metadata.xml
Downloading: http://maven.eea.sk/artifactory/public/eu/unifiedviews/plugins/quality/qualitygraph/uv-q-qualityOntology/0.0.1-SNAPSHOT/uv-q-qualityOntology-0.0.1-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.889s
[INFO] Finished at: Mon Mar 30 10:42:35 CEST 2015
[INFO] Final Memory: 10M/24M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project Q-CU1: Could not resolve dependencies for project eu.unifiedviews:Q-CU1:bundle:1.0.0: Could not find artifact eu.unifiedviews.plugins.quality.qualitygraph:uv-q-qualityOntology:jar:0.0.1-SNAPSHOT in maven.eea.sk (http://maven.eea.sk/artifactory/public/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
